<template>
  <div>
    <h1>Vue.js</h1>
    <p class="description">{{ description }}</p>
    <div>Generated by <code>vue-cli</code> using <a href="https://github.com/vuejs-templates" target="_blank">vuejs-templates/webpack</a></div>
    <div class="mt-5">
      <router-link to="starter" class="btn btn-primary">Back</router-link>
    </div>
  </div>
</template>

<script>
import service from '../../services/'

export default {
  name: 'vuejs',
  data () {
    return {
      description: ''
    }
  },
  beforeRouteEnter (to, from, next) {
    service.getTechnologyDetails('vuejs').then((data) => {
      next(vm => {
        vm.description = data.description
      })
    })
  }
}
</script>

<style scoped>

</style>
